// 遊戲數值資料：建築、單位、年代、科技

export const TILE = 32;
export const MAP_W = 50; // 格數
export const MAP_H = 38;

export const AGES = [
  { id: 0, name: '黑暗時代', nextCost: null },
  {
    id: 1,
    name: '封建時代',
    nextCost: { food: 400, wood: 200 },
    researchTime: 25,
    unlocks: ['ArcheryRange', 'Stable', 'Blacksmith', 'LumberCamp', 'MiningCamp'],
  },
  {
    id: 2,
    name: '城堡時代',
    nextCost: { food: 700, gold: 400 },
    researchTime: 35,
    unlocks: [],
  },
];

// 建築定義
export const BUILDINGS = {
  TownCenter: {
    name: '城鎮中心',
    hp: 1500,
    size: 3,
    cost: {},
    buildTime: 0,
    trains: ['Villager'],
    dropOff: ['wood', 'food', 'gold'],
    pop: 5,
    canAgeUp: true,
    sight: 8,
  },
  House: {
    name: '房屋',
    hp: 250,
    size: 2,
    cost: { wood: 30 },
    buildTime: 12,
    pop: 5,
    sight: 4,
  },
  Barracks: {
    name: '兵營',
    hp: 600,
    size: 3,
    cost: { wood: 150 },
    buildTime: 18,
    trains: ['Militia', 'Spearman'],
    sight: 5,
  },
  ArcheryRange: {
    name: '射箭場',
    hp: 600,
    size: 3,
    cost: { wood: 175 },
    buildTime: 20,
    trains: ['Archer'],
    requiresAge: 1,
    sight: 5,
  },
  Stable: {
    name: '馬廄',
    hp: 600,
    size: 3,
    cost: { wood: 175 },
    buildTime: 20,
    trains: ['Scout'],
    requiresAge: 1,
    sight: 5,
  },
  Blacksmith: {
    name: '鐵匠鋪',
    hp: 500,
    size: 3,
    cost: { wood: 150 },
    buildTime: 18,
    researches: ['Forging', 'ScaleMailArmor', 'Fletching', 'BitDesign'],
    requiresAge: 1,
    sight: 4,
  },
  Farm: {
    name: '農場',
    hp: 150,
    size: 2,
    cost: { wood: 60 },
    buildTime: 10,
    isFarm: true,
    foodAmount: 300,
    sight: 3,
  },
  LumberCamp: {
    name: '伐木場',
    hp: 400,
    size: 2,
    cost: { wood: 100 },
    buildTime: 12,
    dropOff: ['wood'],
    requiresAge: 1,
    sight: 4,
  },
  MiningCamp: {
    name: '採礦場',
    hp: 400,
    size: 2,
    cost: { wood: 100 },
    buildTime: 12,
    dropOff: ['gold'],
    requiresAge: 1,
    sight: 4,
  },
};

// 單位定義。attack/armor/hp 為基礎值，會被科技加成修改（存於 player.techBonus）
export const UNITS = {
  Villager: {
    name: '村民',
    hp: 30,
    attack: 3,
    armor: 0,
    range: 0,
    speed: 50,
    cost: { food: 50 },
    trainTime: 12,
    gatherRate: 0.42,
    carryCap: 10,
    canBuild: true,
    canGather: true,
    class: 'villager',
    radius: 9,
  },
  Militia: {
    name: '長矛民兵',
    hp: 40,
    attack: 4,
    armor: 1,
    range: 0,
    speed: 48,
    cost: { food: 60, gold: 20 },
    trainTime: 16,
    class: 'infantry',
    radius: 10,
    upgradeTo: 'Swordsman',
  },
  Swordsman: {
    name: '劍士',
    hp: 60,
    attack: 9,
    armor: 2,
    range: 0,
    speed: 48,
    cost: { food: 60, gold: 20 },
    trainTime: 16,
    class: 'infantry',
    radius: 10,
    upgradeTo: 'LongSwordsman',
  },
  LongSwordsman: {
    name: '長劍士',
    hp: 75,
    attack: 12,
    armor: 3,
    range: 0,
    speed: 48,
    cost: { food: 70, gold: 25 },
    trainTime: 18,
    class: 'infantry',
    radius: 10,
  },
  Spearman: {
    name: '長槍兵',
    hp: 45,
    attack: 3,
    armor: 0,
    range: 0,
    speed: 47,
    cost: { food: 35, wood: 25 },
    trainTime: 16,
    requiresAge: 1,
    class: 'infantry',
    bonusVs: { cavalry: 18 },
    radius: 10,
  },
  Archer: {
    name: '弓箭手',
    hp: 30,
    attack: 4,
    armor: 0,
    range: 4 * TILE,
    speed: 46,
    cost: { wood: 25, gold: 45 },
    trainTime: 18,
    requiresAge: 1,
    class: 'archer',
    radius: 9,
    upgradeTo: 'Crossbowman',
    projectileSpeed: 320,
  },
  Crossbowman: {
    name: '弩手',
    hp: 35,
    attack: 6,
    armor: 0,
    range: 4.5 * TILE,
    speed: 46,
    cost: { wood: 25, gold: 45 },
    trainTime: 18,
    class: 'archer',
    radius: 9,
    projectileSpeed: 360,
  },
  Scout: {
    name: '偵察騎兵',
    hp: 45,
    attack: 3,
    armor: 2,
    range: 0,
    speed: 85,
    cost: { food: 80 },
    trainTime: 20,
    requiresAge: 1,
    class: 'cavalry',
    radius: 11,
    upgradeTo: 'Knight',
  },
  Knight: {
    name: '騎士',
    hp: 100,
    attack: 10,
    armor: 2,
    range: 0,
    speed: 85,
    cost: { food: 90, gold: 30 },
    trainTime: 22,
    class: 'cavalry',
    radius: 11,
  },
};

// 兵營/馬廄/射箭場內可研究的兵種升級（花費+時間），觸發後把某類別已存在單位全部替換數值並改變之後訓練的單位種類
export const UNIT_UPGRADES = {
  Swordsman: { name: '劍士升級', cost: { food: 100, gold: 30 }, time: 20, requiresAge: 1, from: 'Militia', building: 'Barracks' },
  LongSwordsman: { name: '長劍士升級', cost: { food: 150, gold: 60 }, time: 25, requiresAge: 2, from: 'Swordsman', building: 'Barracks' },
  Crossbowman: { name: '弩手升級', cost: { wood: 100, gold: 80 }, time: 25, requiresAge: 2, from: 'Archer', building: 'ArcheryRange' },
  Knight: { name: '騎士升級', cost: { food: 150, gold: 100 }, time: 25, requiresAge: 2, from: 'Scout', building: 'Stable' },
};

// 鐵匠鋪科技：對特定兵種類別加成攻擊/護甲
export const TECHS = {
  Forging: { name: '鍛造術（步兵攻擊+2）', cost: { food: 150, gold: 0 }, time: 20, requiresAge: 1, effect: { class: 'infantry', attack: 2 } },
  ScaleMailArmor: { name: '鱗甲術（步兵護甲+1）', cost: { food: 100, gold: 50 }, time: 20, requiresAge: 1, effect: { class: 'infantry', armor: 1 } },
  Fletching: { name: '箭術（弓兵攻擊+2）', cost: { wood: 100, gold: 50 }, time: 20, requiresAge: 1, effect: { class: 'archer', attack: 2 } },
  BitDesign: { name: '馬具術（騎兵速度+15%）', cost: { food: 100, gold: 50 }, time: 20, requiresAge: 1, effect: { class: 'cavalry', speedMul: 1.15 } },
};

export const RESOURCE_TYPES = ['wood', 'food', 'gold'];

export const STARTING_RESOURCES = { wood: 200, food: 200, gold: 100 };
export const STARTING_POP_CAP = 5;
export const MAX_POP_CAP = 100;
